name: at_dart
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  at_client: ^3.0.63
  at_utils: ^3.0.15
  at_onboarding_cli: ^1.3.0
  chalkdart: ^2.0.9
  logging: ^1.2.0
  at_cli_commons: ^1.0.3

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
