name: Add binaries to release
run-name: Add binaries to release ${{ github.event.release.tag_name }}

on:
  release:
    types:
      - created

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  upload:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            output-name: twh-linux-x64
            ext: ''
            bundle: 'shell'
          - os: macos-13
            output-name: thw-macos-x64
            ext: ''
            bundle: 'shell'
          - os: macos-14
            output-name: thw-macos-arm64
            ext: ''
            bundle: 'shell'
          - os: windows-latest
            output-name: twh-windows-x64
            ext: '.exe'
            bundle: 'windows'
    runs-on: ${{ matrix.os }}
    name: Upload ${{ matrix.os }} binaries to release ${{ github.event.release.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - uses: dart-lang/setup-dart@v1.6.5
        with:
          sdk: stable
      - name: compile
        shell: bash
        run: |
          cd packages/dart/twh_tools
          mkdir twh
          mkdir tarball
          dart pub get
          dart analyze
          export DART_BINS=$(ls bin/*.dart)
          for dart_file in $DART_BINS; do
              echo "Compiling $dart_file"
              bin_name=${dart_file%.dart}
              bin_name=${bin_name#bin/}
              bin_name=$bin_name${{ matrix.ext }}
              echo $bin_name
              dart compile exe -o twh/$bin_name $dart_file
          done
          chmod +x twh/*
      # zip the build
      - if: ${{ matrix.os == 'macos-13' || matrix.os == 'macos-14' }}
        run: ditto -c -k --keepParent twh tarball/${{ matrix.output-name }}.zip
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: tar -cvzf tarball/${{ matrix.output-name }}.tgz twh
      - if: ${{ matrix.os == 'windows-latest' }}
        run: Compress-Archive -Path twh -Destination tarball/${{ matrix.output-name }}.zip

      # notarize the build
      - if: ${{ matrix.os == 'macos-13' || matrix.os == 'macos-14' }}
        env:
          MACOS_APPLE_ID: ${{ secrets.MACOS_APPLE_ID }}
          MACOS_TEAM_ID: ${{ secrets.MACOS_TEAM_ID }}
          MACOS_APPLE_ID_PASSWORD: ${{ secrets.MACOS_APPLE_ID_PASSWORD }}
        run: |
          xcrun notarytool submit tarball/${{ matrix.output-name }}.zip \
            --apple-id "$MACOS_APPLE_ID" \
            --team-id "$MACOS_TEAM_ID" \
            --password "$MACOS_APPLE_ID_PASSWORD" \
            --wait
      - name: upload
        shell: bash
        run: |
          export TARGET_GZ=${{ matrix.output-name }}_${{ github.event.release.tag_name }}*
          tar -czvf $TARGET_GZ twh/*
          gh release upload ${{ github.event.release.tag_name }} $TARGET_GZ
    